//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Main
{
    public static class MainView
    {
        public static readonly string Title = "Localization.Main.MainView.Title";
        public static readonly string Subtitle = "Localization.Main.MainView.Subtitle";
        public static readonly string ChangeLanguage = "Localization.Main.MainView.ChangeLanguage";
        public static readonly string RuntimeTitle = "Localization.Main.MainView.RuntimeTitle";
        public static readonly string CurrentCulture = "Localization.Main.MainView.CurrentCulture";
        public static readonly string CurrentTimeFormat = "Localization.Main.MainView.CurrentTimeFormat";
        public static readonly string RunningCountInfo = "Localization.Main.MainView.RunningCountInfo";
        public static readonly string ResourceKey = "Localization.Main.MainView.ResourceKey";
        public static readonly string ProviderTitle = "Localization.Main.MainView.ProviderTitle";
        public static readonly string ProviderDescription = "Localization.Main.MainView.ProviderDescription";
        public static readonly string StorageTitle = "Localization.Main.MainView.StorageTitle";
        public static readonly string StorageDescription = "Localization.Main.MainView.StorageDescription";
        public static readonly string FixedCultureTitle = "Localization.Main.MainView.FixedCultureTitle";
        public static readonly string EnglishPreview = "Localization.Main.MainView.EnglishPreview";
        public static readonly string JapanesePreview = "Localization.Main.MainView.JapanesePreview";
        public static readonly string SimplifiedChinesePreview = "Localization.Main.MainView.SimplifiedChinesePreview";
        public static readonly string TraditionalChinesePreview = "Localization.Main.MainView.TraditionalChinesePreview";
        public static readonly string FallbackTitle = "Localization.Main.MainView.FallbackTitle";
        public static readonly string FallbackDescription = "Localization.Main.MainView.FallbackDescription";
        public static readonly string BindingRefresh = "Localization.Main.MainView.BindingRefresh";
        public static readonly string CultureCardTitle = "Localization.Main.MainView.CultureCardTitle";
        public static readonly string ClockCardTitle = "Localization.Main.MainView.ClockCardTitle";
        public static readonly string PlatformCardTitle = "Localization.Main.MainView.PlatformCardTitle";
        public static readonly string ResourceCardTitle = "Localization.Main.MainView.ResourceCardTitle";
    }

}
namespace Localization.DevelopModule
{
    public static class ResourcePipelineView
    {
        public static readonly string Title = "Localization.DevelopModule.ResourcePipelineView.Title";
        public static readonly string Description = "Localization.DevelopModule.ResourcePipelineView.Description";
        public static readonly string FormatSupport = "Localization.DevelopModule.ResourcePipelineView.FormatSupport";
        public static readonly string HotSwitch = "Localization.DevelopModule.ResourcePipelineView.HotSwitch";
        public static readonly string Fallback = "Localization.DevelopModule.ResourcePipelineView.Fallback";
        public static readonly string StrongKeys = "Localization.DevelopModule.ResourcePipelineView.StrongKeys";
    }

    public static class ValidationView
    {
        public static readonly string Title = "Localization.DevelopModule.ValidationView.Title";
        public static readonly string Description = "Localization.DevelopModule.ValidationView.Description";
        public static readonly string MissingKeyPolicy = "Localization.DevelopModule.ValidationView.MissingKeyPolicy";
        public static readonly string ThreadCulture = "Localization.DevelopModule.ValidationView.ThreadCulture";
        public static readonly string EmbeddedResources = "Localization.DevelopModule.ValidationView.EmbeddedResources";
        public static readonly string AnalyzerSupport = "Localization.DevelopModule.ValidationView.AnalyzerSupport";
    }

}
