//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lang.Avalonia.Resx.Demo.I18n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lang.Avalonia.Resx.Demo.I18n.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Maximum length 的本地化字符串。
        /// </summary>
        internal static string Localization_DevelopModule_SettingView_MaxLength {
            get {
                return ResourceManager.GetString("Localization.DevelopModule.SettingView.MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string Localization_DevelopModule_SettingView_Title {
            get {
                return ResourceManager.GetString("Localization.DevelopModule.SettingView.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert 的本地化字符串。
        /// </summary>
        internal static string Localization_DevelopModule_Title2SlugView_Convert {
            get {
                return ResourceManager.GetString("Localization.DevelopModule.Title2SlugView.Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convert article title to URL slug 的本地化字符串。
        /// </summary>
        internal static string Localization_DevelopModule_Title2SlugView_Title {
            get {
                return ResourceManager.GetString("Localization.DevelopModule.Title2SlugView.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch language 的本地化字符串。
        /// </summary>
        internal static string Localization_Main_MainView_ChangeLanguage {
            get {
                return ResourceManager.GetString("Localization.Main.MainView.ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The current time is {0} 的本地化字符串。
        /// </summary>
        internal static string Localization_Main_MainView_CurrentTimeFormat {
            get {
                return ResourceManager.GetString("Localization.Main.MainView.CurrentTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit the program 的本地化字符串。
        /// </summary>
        internal static string Localization_Main_MainView_Exit {
            get {
                return ResourceManager.GetString("Localization.Main.MainView.Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Running {0} operating system, {1} 的本地化字符串。
        /// </summary>
        internal static string Localization_Main_MainView_RunningCountInfo {
            get {
                return ResourceManager.GetString("Localization.Main.MainView.RunningCountInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Implement internationalization using XML 的本地化字符串。
        /// </summary>
        internal static string Localization_Main_MainView_Title {
            get {
                return ResourceManager.GetString("Localization.Main.MainView.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Don&apos;t prompt again 的本地化字符串。
        /// </summary>
        internal static string Localization_Main_SettingView_NoPrompt {
            get {
                return ResourceManager.GetString("Localization.Main.SettingView.NoPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string Localization_Main_SettingView_Title {
            get {
                return ResourceManager.GetString("Localization.Main.SettingView.Title", resourceCulture);
            }
        }
    }
}
