//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Lang.Avalonia.Resx.Demo.I18n
{
    internal class Resources
    {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal Resources()

        {
        }

        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    resourceMan = new global::System.Resources.ResourceManager("Lang.Avalonia.Resx.Demo.I18n.Resources", typeof(Resources).Assembly);
                }

                return resourceMan;
            }
        }

        internal static global::System.Globalization.CultureInfo Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        internal static string Localization_Main_MainView_Title => ResourceManager.GetString("Localization.Main.MainView.Title", resourceCulture);

        internal static string Localization_Main_MainView_Subtitle => ResourceManager.GetString("Localization.Main.MainView.Subtitle", resourceCulture);

        internal static string Localization_Main_MainView_ChangeLanguage => ResourceManager.GetString("Localization.Main.MainView.ChangeLanguage", resourceCulture);

        internal static string Localization_Main_MainView_RuntimeTitle => ResourceManager.GetString("Localization.Main.MainView.RuntimeTitle", resourceCulture);

        internal static string Localization_Main_MainView_CurrentCulture => ResourceManager.GetString("Localization.Main.MainView.CurrentCulture", resourceCulture);

        internal static string Localization_Main_MainView_CurrentTimeFormat => ResourceManager.GetString("Localization.Main.MainView.CurrentTimeFormat", resourceCulture);

        internal static string Localization_Main_MainView_RunningCountInfo => ResourceManager.GetString("Localization.Main.MainView.RunningCountInfo", resourceCulture);

        internal static string Localization_Main_MainView_ResourceKey => ResourceManager.GetString("Localization.Main.MainView.ResourceKey", resourceCulture);

        internal static string Localization_Main_MainView_ProviderTitle => ResourceManager.GetString("Localization.Main.MainView.ProviderTitle", resourceCulture);

        internal static string Localization_Main_MainView_ProviderDescription => ResourceManager.GetString("Localization.Main.MainView.ProviderDescription", resourceCulture);

        internal static string Localization_Main_MainView_StorageTitle => ResourceManager.GetString("Localization.Main.MainView.StorageTitle", resourceCulture);

        internal static string Localization_Main_MainView_StorageDescription => ResourceManager.GetString("Localization.Main.MainView.StorageDescription", resourceCulture);

        internal static string Localization_Main_MainView_FixedCultureTitle => ResourceManager.GetString("Localization.Main.MainView.FixedCultureTitle", resourceCulture);

        internal static string Localization_Main_MainView_EnglishPreview => ResourceManager.GetString("Localization.Main.MainView.EnglishPreview", resourceCulture);

        internal static string Localization_Main_MainView_JapanesePreview => ResourceManager.GetString("Localization.Main.MainView.JapanesePreview", resourceCulture);

        internal static string Localization_Main_MainView_SimplifiedChinesePreview => ResourceManager.GetString("Localization.Main.MainView.SimplifiedChinesePreview", resourceCulture);

        internal static string Localization_Main_MainView_TraditionalChinesePreview => ResourceManager.GetString("Localization.Main.MainView.TraditionalChinesePreview", resourceCulture);

        internal static string Localization_Main_MainView_FallbackTitle => ResourceManager.GetString("Localization.Main.MainView.FallbackTitle", resourceCulture);

        internal static string Localization_Main_MainView_FallbackDescription => ResourceManager.GetString("Localization.Main.MainView.FallbackDescription", resourceCulture);

        internal static string Localization_Main_MainView_BindingRefresh => ResourceManager.GetString("Localization.Main.MainView.BindingRefresh", resourceCulture);

        internal static string Localization_Main_MainView_CultureCardTitle => ResourceManager.GetString("Localization.Main.MainView.CultureCardTitle", resourceCulture);

        internal static string Localization_Main_MainView_ClockCardTitle => ResourceManager.GetString("Localization.Main.MainView.ClockCardTitle", resourceCulture);

        internal static string Localization_Main_MainView_PlatformCardTitle => ResourceManager.GetString("Localization.Main.MainView.PlatformCardTitle", resourceCulture);

        internal static string Localization_Main_MainView_ResourceCardTitle => ResourceManager.GetString("Localization.Main.MainView.ResourceCardTitle", resourceCulture);

        internal static string Localization_DevelopModule_ResourcePipelineView_Title => ResourceManager.GetString("Localization.DevelopModule.ResourcePipelineView.Title", resourceCulture);

        internal static string Localization_DevelopModule_ResourcePipelineView_Description => ResourceManager.GetString("Localization.DevelopModule.ResourcePipelineView.Description", resourceCulture);

        internal static string Localization_DevelopModule_ResourcePipelineView_FormatSupport => ResourceManager.GetString("Localization.DevelopModule.ResourcePipelineView.FormatSupport", resourceCulture);

        internal static string Localization_DevelopModule_ResourcePipelineView_HotSwitch => ResourceManager.GetString("Localization.DevelopModule.ResourcePipelineView.HotSwitch", resourceCulture);

        internal static string Localization_DevelopModule_ResourcePipelineView_Fallback => ResourceManager.GetString("Localization.DevelopModule.ResourcePipelineView.Fallback", resourceCulture);

        internal static string Localization_DevelopModule_ResourcePipelineView_StrongKeys => ResourceManager.GetString("Localization.DevelopModule.ResourcePipelineView.StrongKeys", resourceCulture);

        internal static string Localization_DevelopModule_ValidationView_Title => ResourceManager.GetString("Localization.DevelopModule.ValidationView.Title", resourceCulture);

        internal static string Localization_DevelopModule_ValidationView_Description => ResourceManager.GetString("Localization.DevelopModule.ValidationView.Description", resourceCulture);

        internal static string Localization_DevelopModule_ValidationView_MissingKeyPolicy => ResourceManager.GetString("Localization.DevelopModule.ValidationView.MissingKeyPolicy", resourceCulture);

        internal static string Localization_DevelopModule_ValidationView_ThreadCulture => ResourceManager.GetString("Localization.DevelopModule.ValidationView.ThreadCulture", resourceCulture);

        internal static string Localization_DevelopModule_ValidationView_EmbeddedResources => ResourceManager.GetString("Localization.DevelopModule.ValidationView.EmbeddedResources", resourceCulture);

        internal static string Localization_DevelopModule_ValidationView_AnalyzerSupport => ResourceManager.GetString("Localization.DevelopModule.ValidationView.AnalyzerSupport", resourceCulture);
    }
}
