<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <AvaloniaVersion>12.1.2</AvaloniaVersion>
    <CodeAnalysisVersion>5.9.0</CodeAnalysisVersion>
    <PrismAvaloniaVersion>8.1.97.11073</PrismAvaloniaVersion>
    <ReactiveUIAvaloniaVersion>12.1.2</ReactiveUIAvaloniaVersion>
    <SemiAvaloniaVersion>12.1.0.1</SemiAvaloniaVersion>
    <SystemDrawingCommonVersion>10.0.11</SystemDrawingCommonVersion>
    <SystemTextJsonVersion>10.0.11</SystemTextJsonVersion>
    <UrsaVersion>2.2.0</UrsaVersion>
    <YYThunksVersion>1.2.2</YYThunksVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Avalonia.Desktop" Version="$(AvaloniaVersion)" />
    <PackageVersion Include="Irihi.Ursa" Version="$(UrsaVersion)" />
    <PackageVersion Include="Irihi.Ursa.Themes.Semi" Version="$(UrsaVersion)" />
    <PackageVersion Include="Semi.Avalonia" Version="$(SemiAvaloniaVersion)" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="$(CodeAnalysisVersion)" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="$(CodeAnalysisVersion)" />
    <PackageVersion Include="Prism.Avalonia" Version="$(PrismAvaloniaVersion)" />
    <PackageVersion Include="Prism.DryIoc.Avalonia" Version="$(PrismAvaloniaVersion)" />
    <PackageVersion Include="ReactiveUI.Avalonia" Version="$(ReactiveUIAvaloniaVersion)" />
    <PackageVersion Include="System.Drawing.Common" Version="$(SystemDrawingCommonVersion)" />
    <PackageVersion Include="System.Text.Json" Version="$(SystemTextJsonVersion)" />
    <PackageVersion Include="VC-LTL" Version="5.3.1" />
    <PackageVersion Include="YY-Thunks" Version="$(YYThunksVersion)" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.401" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>
