//------------------------------------------------------------------------------  
// <auto-generated>  
//     This code was generated by a tool.  
//     Changes to this file may cause incorrect behavior and will be lost if  
//     the code is regenerated.  
// </auto-generated>  
//------------------------------------------------------------------------------
namespace Localization.Main
{
    public static class MainView
    {
        public static readonly string Title = "Localization.Main.MainView.Title";
        public static readonly string Subtitle = "Localization.Main.MainView.Subtitle";
        public static readonly string Language = "Localization.Main.MainView.Language";
        public static readonly string DiagnosticsTitle = "Localization.Main.MainView.DiagnosticsTitle";
        public static readonly string Footer = "Localization.Main.MainView.Footer";
    }


}


