using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Lang.Avalonia.Analysis;

internal static class LanguageCodeGenerator
{
    internal static string GenerateLanguageConstants(Dictionary<string, Dictionary<string, string>> allResources)
    {
        if (!allResources.Any())
        {
            return string.Empty;
        }

        var stringBuilder = new StringBuilder();

        // 添加文件头注释
        stringBuilder.AppendLine("//------------------------------------------------------------------------------");
        stringBuilder.AppendLine("// <auto-generated>");
        stringBuilder.AppendLine("//     This code was generated by Lang.Avalonia.Analysis.");
        stringBuilder.AppendLine("//     Changes to this file may cause incorrect behavior and will be lost if");
        stringBuilder.AppendLine("//     the code is regenerated.");
        stringBuilder.AppendLine("// </auto-generated>");
        stringBuilder.AppendLine("//------------------------------------------------------------------------------");
        stringBuilder.AppendLine();

        var resourceKeys = allResources.Values
            .SelectMany(resources => resources.Keys)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(key => key, StringComparer.Ordinal);
        var classStructure = AnalyzeResourceStructure(resourceKeys);

        // 生成命名空间
        foreach (var namespaceGroup in classStructure.OrderBy(group => group.Key, StringComparer.Ordinal))
        {
            var namespaceName = namespaceGroup.Key;
            var classes = namespaceGroup.Value;

            stringBuilder.AppendLine($"namespace {namespaceName}");
            stringBuilder.AppendLine("{");

            // 生成类
            foreach (var classGroup in classes.OrderBy(group => group.Key, StringComparer.Ordinal))
            {
                var className = classGroup.Key;
                var properties = classGroup.Value;

                stringBuilder.AppendLine($"    public static class {className}");
                stringBuilder.AppendLine("    {");

                // 生成属性
                var usedNames = new HashSet<string>();
                foreach (var property in properties
                             .OrderBy(p => p.PropertyName, StringComparer.Ordinal)
                             .ThenBy(p => p.ResourceKey, StringComparer.Ordinal))
                {
                    var propertyName = GetUniqueName(SanitizeName(property.PropertyName), usedNames);
                    stringBuilder.AppendLine($"        public static readonly string {propertyName} = \"{EscapeStringLiteral(property.ResourceKey)}\";");
                }

                stringBuilder.AppendLine("    }");
                stringBuilder.AppendLine();
            }

            stringBuilder.AppendLine("}");
            stringBuilder.AppendLine();
        }

        return stringBuilder.ToString();
    }

    private static Dictionary<string, Dictionary<string, List<(string PropertyName, string ResourceKey)>>> AnalyzeResourceStructure(IEnumerable<string> resourceKeys)
    {
        var result = new Dictionary<string, Dictionary<string, List<(string PropertyName, string ResourceKey)>>>();

        foreach (var key in resourceKeys)
        {
            var parts = key.Split('.');
            if (parts.Length < 3)
            {
                continue; // 至少需要 namespace.class.property
            }

            // 找到根命名空间（通常是最长的公共前缀）
            var namespacePart = SanitizeName(parts[0]);
            var modulePart = SanitizeName(parts[1]);
            var classPart = SanitizeName(parts[2]);
            var propertyPart = string.Join(".", parts.Skip(3));

            if (string.IsNullOrEmpty(propertyPart))
            {
                propertyPart = classPart;
            }

            var fullNamespace = $"{namespacePart}.{modulePart}";

            if (!result.ContainsKey(fullNamespace))
            {
                result[fullNamespace] = new Dictionary<string, List<(string PropertyName, string ResourceKey)>>();
            }

            if (!result[fullNamespace].ContainsKey(classPart))
            {
                result[fullNamespace][classPart] = new List<(string PropertyName, string ResourceKey)>();
            }

            result[fullNamespace][classPart].Add((propertyPart, key));
        }

        return result;
    }

    private static string SanitizeName(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return "Unnamed";
        }

        var sanitized = new string(name.Select(c => char.IsLetterOrDigit(c) || c == '_' ? c : '_').ToArray());

        // 确保不以数字开头
        if (sanitized.Length > 0 && char.IsDigit(sanitized[0]))
        {
            sanitized = "_" + sanitized;
        }

        if (SyntaxFacts.GetKeywordKind(sanitized) != SyntaxKind.None
            || SyntaxFacts.GetContextualKeywordKind(sanitized) != SyntaxKind.None)
        {
            sanitized = "_" + sanitized;
        }

        return sanitized.Length == 0 ? "Unnamed" : sanitized;
    }

    private static string GetUniqueName(string name, HashSet<string> usedNames)
    {
        if (usedNames.Add(name))
        {
            return name;
        }

        var index = 2;
        while (!usedNames.Add($"{name}{index}"))
        {
            index++;
        }

        return $"{name}{index}";
    }

    private static string EscapeStringLiteral(string value)
    {
        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\r", "\\r")
            .Replace("\n", "\\n")
            .Replace("\t", "\\t")
            .Replace("\b", "\\b")
            .Replace("\f", "\\f");
    }
}
